app:
  replicaCount: 1
  image:
    repository: ghcr.io/xputraade/devops-demo
    tag: "gitops-demo-v2"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30081
